### ISSUE TITLE
Creating extension before adding it to shared_preload_libraries crashes postmaster

### ISSUE THREAD

**Issue by devrimgunduz** [pierreforstmann/pg_readonly#3]
Hi,

Postmaster crashes when I wanted to create the extension before adding it to shared_preload_libraries. I think extension should check shared_preload_libraries first before running. If my memory serves well, Citus does this (if you want to take a look how that is done). This is the related part of the logs:

> LOG:  pg_readonly:_PG_init(): pg_readonly extension is enabled
> STATEMENT:  CREATE EXTENSION pg_readonly ;
> LOG:  server process (PID 312910) was terminated by signal 11: Segmentation fault
> DETAIL:  Failed process was running: CREATE EXTENSION pg_readonly ;
> LOG:  terminating any other active server processes
> WARNING:  terminating connection because of crash of another server process

Thanks!

Devrim

**Comment by pierreforstmann** [comment]
Hello,
I have fixed this issue with today's commit.

Thanks for reporting.

Pierre

**Comment by pierreforstmann** [comment]
I have also disabled SQL functions if extension is not enabled with today's commit.
