### ISSUE TITLE
I like pg_readonly()

### ISSUE THREAD

**Issue by luss** [pierreforstmann/pg_readonly#7]
Hi Pierre,

It's very interesting to me and I'm taking a closer look at it.  I have created a public fork called pgedge/readonly.
I've made some basic/simple/recommended changes and created a tag call v1.1.0.   The non cosmetic change is to "formally" drop support in the extension for "formally unsupported" versions of PostgreSQL (9.5, 9.6 & 10).  I also named the new/same control sql file --1.1 instead of calling it --1.1.0.  Yes, this correctly implies the intent to not change any function signatures unless we bump to --1.2.  A minor version, such as support for pg16 when it comes out, would be tagged as v1.1.1.

I'd love to know if you agree with my thinking on these little things and if you'd like me to submit a pull request.

--Luss

**Comment by pierreforstmann** [comment]
Hello Denis,

Yes, I agree with your modifications and you can submit a pull request.

Thanks.
